-- 0009_locations.sql
-- GENERATED by scripts/gen-locations-sql.mjs from data/market.js. Do not edit
-- by hand; edit data/market.js and regenerate.
--
-- Brings the cities and neighborhoods tables in line with every place the
-- listing form offers (22 cities, 52 neighbourhoods). Without it, choosing an
-- area that exists only in the app fails the insert with
-- "violates foreign key constraint properties_neighborhood_id_fkey".
--
-- Safe to run more than once: rows are upserted, never duplicated, and no
-- listing is touched.

insert into public.cities (id, name_en, name_ar, lat, lng) values
  ('amman', 'Amman', 'عمان', 31.953, 35.91),
  ('zarqa', 'Zarqa', 'الزرقاء', 32.072, 36.088),
  ('irbid', 'Irbid', 'إربد', 32.556, 35.847),
  ('aqaba', 'Aqaba', 'العقبة', 29.532, 35.006),
  ('salt', 'Salt', 'السلط', 32.038, 35.727),
  ('madaba', 'Madaba', 'مأدبا', 31.716, 35.795),
  ('jerash', 'Jerash', 'جرش', 32.282, 35.896),
  ('mafraq', 'Mafraq', 'المفرق', 32.343, 36.208),
  ('ajloun', 'Ajloun', 'عجلون', 32.333, 35.752),
  ('karak', 'Karak', 'الكرك', 31.185, 35.702),
  ('tafilah', 'Tafilah', 'الطفيلة', 30.837, 35.604),
  ('maan', 'Ma’an', 'معان', 30.192, 35.734),
  ('ramtha', 'Ramtha', 'الرمثا', 32.561, 36.008),
  ('russeifa', 'Russeifa', 'الرصيفة', 32.018, 36.046),
  ('sahab', 'Sahab', 'سحاب', 31.87, 36.005),
  ('fuheis', 'Fuheis', 'الفحيص', 32.008, 35.774),
  ('mahis', 'Mahis', 'ماحص', 31.995, 35.76),
  ('deadsea', 'Dead Sea', 'البحر الميت', 31.502, 35.583),
  ('wadimusa', 'Wadi Musa', 'وادي موسى', 30.322, 35.478),
  ('wadirum', 'Wadi Rum', 'وادي رم', 29.575, 35.42),
  ('azraq', 'Azraq', 'الأزرق', 31.834, 36.816),
  ('dhiban', 'Dhiban', 'ذيبان', 31.5, 35.783)
on conflict (id) do update
  set name_en = excluded.name_en,
      name_ar = excluded.name_ar,
      lat     = excluded.lat,
      lng     = excluded.lng;

insert into public.neighborhoods (id, city_id, name_en, name_ar, lat, lng, aliases) values
  ('abdoun', 'amman', 'Abdoun', 'عبدون', 31.936, 35.879, array['abdon', 'abdoun al shamali', 'abdoon']::text[]),
  ('sweifieh', 'amman', 'Sweifieh', 'الصويفية', 31.949, 35.867, array['swaifieh', 'sweifiyeh', 'swefieh']::text[]),
  ('khalda', 'amman', 'Khalda', 'خلدا', 31.987, 35.826, array['khaldah', 'khalida']::text[]),
  ('dabouq', 'amman', 'Dabouq', 'دابوق', 31.986, 35.786, array['daboug', 'dabuq', 'dabok']::text[]),
  ('jabalamman', 'amman', 'Jabal Amman', 'جبل عمان', 31.951, 35.925, array['first circle', 'third circle']::text[]),
  ('deirghbar', 'amman', 'Deir Ghbar', 'دير غبار', 31.945, 35.858, array['der ghbar', 'deir ghubar']::text[]),
  ('umuthaina', 'amman', 'Um Uthaina', 'أم أذينة', 31.964, 35.872, array['umm uthaina', 'om uthaina']::text[]),
  ('shmeisani', 'amman', 'Shmeisani', 'الشميساني', 31.968, 35.905, array['shmaisani', 'shmesani']::text[]),
  ('abdali', 'amman', 'Abdali', 'العبدلي', 31.962, 35.914, array['al abdali', 'abdali boulevard']::text[]),
  ('airportrd', 'amman', 'Airport Road', 'طريق المطار', 31.855, 35.95, array['airport street']::text[]),
  ('tlaalali', 'amman', 'Tla’ Al Ali', 'تلاع العلي', 31.987, 35.862, array['tla al ali', 'tlaa al ali', 'telaa al ali']::text[]),
  ('jubaiha', 'amman', 'Al Jubaiha', 'الجبيهة', 32.02, 35.874, array['jubeiha', 'jbeiha']::text[]),
  ('marj', 'amman', 'Marj Al Hamam', 'مرج الحمام', 31.888, 35.836, array['marj el hamam']::text[]),
  ('rabieh', 'amman', 'Al Rabieh', 'الرابية', 31.971, 35.87, array['rabiah', 'rabya', 'al rabiyeh']::text[]),
  ('jabalhussein', 'amman', 'Jabal Al Hussein', 'جبل الحسين', 31.968, 35.917, array['jabal hussein']::text[]),
  ('weibdeh', 'amman', 'Jabal Al Weibdeh', 'جبل اللويبدة', 31.957, 35.921, array['lweibdeh', 'luweibdeh', 'weibdeh']::text[]),
  ('wadisaqra', 'amman', 'Wadi Saqra', 'وادي صقرة', 31.96, 35.9, array['wadi sakra']::text[]),
  ('gardens', 'amman', 'Gardens Street', 'شارع الجاردنز', 31.977, 35.879, array['wasfi al tal', 'wasfi el tal', 'garden street']::text[]),
  ('meccast', 'amman', 'Mecca Street', 'شارع مكة', 31.972, 35.85, array['makkah street', 'mecca st']::text[]),
  ('umsummaq', 'amman', 'Um Al Summaq', 'أم السماق', 31.976, 35.845, array['umm al summaq', 'om al summaq']::text[]),
  ('sportcity', 'amman', 'Sports City', 'المدينة الرياضية', 31.983, 35.9, array['sport city', 'al medina al riyadiya']::text[]),
  ('shafabadran', 'amman', 'Shafa Badran', 'شفا بدران', 32.043, 35.895, array['shafabadran', 'shafa badran']::text[]),
  ('sweileh', 'amman', 'Sweileh', 'صويلح', 32.028, 35.836, array['suweileh', 'swaileh']::text[]),
  ('abunsair', 'amman', 'Abu Nsair', 'أبو نصير', 32.056, 35.856, array['abu nseir', 'abu naseer']::text[]),
  ('tabarbour', 'amman', 'Tabarbour', 'طبربور', 32.02, 35.925, array['tabarbor']::text[]),
  ('wadiseer', 'amman', 'Wadi Al Seer', 'وادي السير', 31.949, 35.795, array['wadi seer', 'wadi es seer']::text[]),
  ('bayader', 'amman', 'Bayader Wadi Seer', 'بيادر وادي السير', 31.951, 35.815, array['bayader', 'al bayader']::text[]),
  ('kursi', 'amman', 'Al Kursi', 'الكرسي', 31.968, 35.836, array['kursi']::text[]),
  ('dahiyatrashid', 'amman', 'Dahiyat Al Rashid', 'ضاحية الرشيد', 32.006, 35.876, array['dahyat al rashid', 'al rashid suburb']::text[]),
  ('dahiyathussein', 'amman', 'Dahiyat Al Hussein', 'ضاحية الحسين', 31.989, 35.899, array['dahyat al hussein']::text[]),
  ('qweismeh', 'amman', 'Al Qweismeh', 'القويسمة', 31.909, 35.966, array['quweismeh', 'qwaismeh']::text[]),
  ('muqablain', 'amman', 'Al Muqablain', 'المقابلين', 31.905, 35.885, array['mqablain', 'muqabalain']::text[]),
  ('naour', 'amman', 'Naour', 'ناعور', 31.869, 35.822, array['naor', 'na our']::text[]),
  ('marka', 'amman', 'Marka', 'ماركا', 31.972, 35.981, array['marqa']::text[]),
  ('hashmi', 'amman', 'Al Hashmi', 'الهاشمي', 31.968, 35.945, array['hashmi shamali', 'al hashimi']::text[]),
  ('nazzal', 'amman', 'Al Nazzal', 'النزهة', 31.93, 35.925, array['nazzal']::text[]),
  ('downtown', 'amman', 'Downtown', 'وسط البلد', 31.951, 35.935, array['al balad', 'balad', 'city centre', 'city center']::text[]),
  ('jandaweel', 'amman', 'Jandaweel', 'الجندويل', 31.941, 35.849, array['jandweel', 'jandawil']::text[]),
  ('khreibetsouq', 'amman', 'Khreibet Al Souq', 'خريبة السوق', 31.878, 35.928, array['khraibet al souq']::text[]),
  ('yadudeh', 'amman', 'Al Yadudeh', 'اليادودة', 31.855, 35.885, array['yadoudeh', 'yadodeh']::text[]),
  ('southbeach', 'aqaba', 'South Beach', 'الشاطئ الجنوبي', 29.451, 34.986, array[]::text[]),
  ('talabay', 'aqaba', 'Tala Bay', 'تالا باي', 29.396, 34.977, array['talabay']::text[]),
  ('ayla', 'aqaba', 'Ayla', 'أيلة', 29.539, 34.985, array['ayla oasis']::text[]),
  ('aqabacentre', 'aqaba', 'Aqaba Town', 'وسط العقبة', 29.529, 35.006, array['aqaba downtown']::text[]),
  ('irbidcentre', 'irbid', 'Irbid Centre', 'وسط إربد', 32.553, 35.851, array['irbid center', 'irbid downtown']::text[]),
  ('hayjameaa', 'irbid', 'University Area', 'حي الجامعة', 32.531, 35.855, array['hay al jameaa', 'yarmouk university']::text[]),
  ('aidoun', 'irbid', 'Aidoun', 'عيدون', 32.542, 35.881, array['aydoun', 'eidoun']::text[]),
  ('zarqacentre', 'zarqa', 'Zarqa Centre', 'وسط الزرقاء', 32.073, 36.089, array['zarqa center']::text[]),
  ('jabaltaj', 'zarqa', 'Jabal Tareq', 'جبل طارق', 32.06, 36.1, array['jabal tariq']::text[]),
  ('sweimeh', 'deadsea', 'Sweimeh', 'سويمة', 31.51, 35.585, array['swemeh', 'suweimeh']::text[]),
  ('madabacentre', 'madaba', 'Madaba Centre', 'وسط مأدبا', 31.716, 35.794, array['madaba center']::text[]),
  ('safut', 'salt', 'Safut', 'صافوط', 32.028, 35.815, array['safoot']::text[])
on conflict (id) do update
  set city_id = excluded.city_id,
      name_en = excluded.name_en,
      name_ar = excluded.name_ar,
      lat     = excluded.lat,
      lng     = excluded.lng,
      aliases = excluded.aliases;

notify pgrst, 'reload schema';
